appoo/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('members/', include('members.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views


urlpatterns = [
  # path("", hello, name="home"),
  path('admin/', views.admin, name='admin'),
  
  path('', views.home, name='home'),
  path('escala', views.escala, name='escala'),
  path('recomendaciones', views.recomendaciones, name='recomendaciones'),
  path('blog', views.blog, name='blog'),
  path('enlaces', views.enlaces, name='enlaces'),
  path('fotos', views.fotos, name='fotos'),
  # --------------------------------------------
  path('contact', views.contact, name='contact'),
  path('messages', views.message_list, name='message_list'),
  path('mymessages', views.my_messages, name='my_messages'),
  path('messages/<int:pk>/',views.message_detail, name='message_detail'),
  path('messages/<pk>/remove', views.message_remove, name='message_remove'),
  path('sent',views.success, name='success'),
]

web/models.py
from django.db import models

from django.utils import timezone

# Create your models here.
class Funfact(models.Model):
  idm = models.CharField(max_length=100)
  title = models.CharField(max_length=100)
  text = models.CharField(max_length=1000)
  photo = models.ImageField(
    upload_to='media/photo_funfacts',
    default='media/default/default.jpg',
    blank=True)

class Scale(models.Model):
  idm = models.CharField(max_length=100)
  photo = models.ImageField(
    upload_to='media/photo_scale',
    default='media/default/default.jpg',
    blank=True)
  typesb = models.CharField(max_length=100)
  text = models.CharField(max_length=100)
  cause = models.CharField(max_length=100)

class Tip(models.Model):
  ICONS= (
    ('fa-solid fa-droplet','agua'),
    ('fa-solid fa-wheat-awn','comida'),
    ('fa-solid fa-person-running','deporte'),
    ('fa-solid fa-comment-medical','medicamento'),
    ('fa-solid fa-comment','otros'),
  )
  idm = models.CharField(max_length=100)
  title = models.CharField(max_length=100)
  text = models.CharField(max_length=100)
  icon = models.CharField(max_length=100, choices=ICONS)

class Post(models.Model):
  idm = models.CharField(max_length=100)
  title = models.CharField(max_length=100)
  text = models.CharField(max_length=100)
  photo = models.ImageField(
    upload_to='media/photo_posts',
    default='media/default/default.jpg',
    blank=True)

class Link(models.Model):
  ICONS= (
    ('fa-solid fa-globe','web'),
    ('fa-solid fa-house-medical','salud'),
    ('fa-solid fa-link','otros'),
  )
  idm = models.CharField(max_length=100)
  title = models.CharField(max_length=100)
  text = models.CharField(max_length=100)
  icon = models.CharField(max_length=100, choices=ICONS)



class Photo(models.Model):
  idm = models.CharField(max_length=100)
  title = models.CharField(max_length=100)
  text = models.CharField(max_length=1000)
  photo = models.ImageField(
    upload_to='media/photo_gallery',
    default='media/default/default.jpg',
    blank=True)



class Suscriptor(models.Model):
  full_name = models.CharField(max_length=100)
  email = models.CharField(max_length=1000)



class Caca(models.Model):
  tipo = models.CharField(max_length=100)







# -----------------------------------------
class Contact(models.Model): 
  name = models.CharField(max_length=200)
  sender = models.EmailField()
  subject = models.CharField(max_length=200)
  message = models.TextField()
  cc_myself = models.BooleanField(default=False)
  sending_date = models.DateTimeField(blank=True, null=True)

  def sent(self):
    self.sending_date = timezone.now()
    self.save()

  def str(self):
    return self.sender

web/templates/web/_demo_home.html
{% extends 'base-store.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Home</h1>

            <p>Developed and proposed for the first time in
                England by Stephen Lewis and Ken Heaton at
                the University Department of Medicine,
                Bristol Royal Infirmary, it</p>
            <p>The authors as a clinical assessment tool in
                1997 in the Scandinavian Journal of Gastroenterology
                after a previous prospective study, conducted in
                on a sample of the population (838 men and 1,059 women),
                had shown an unexpected prevalence</p>
            <p>Related to the shape and type of stool. The authors of
                the former paper concluded that the form of the stool
                is a useful surrogate measure of colon transit time.</p>
            <p>That conclusion has since been challenged as having limited
                validity for Types 1 and 2; however, it remains in use
                as a research tool to evaluate the effectiveness of
                treatments for various diseases of the bowel, as well as
                a clinical communication aid.</p>

        </div>
    </div>
</div>
{% endblock %}

web/templates/web/blog.html
{% extends 'base-main.html' %}
{% load static %}

{% block title %}Blog{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <h1 class="col s12">Blog</h1>

            <p>Type of stool. The authors of
            the former paper concluded that the form of the stool
            is a useful surrogate measure of colon transit time.
            That conclusion has since e Scandinavian Journal of Gastroenterology
            after a previous prospective study, conducted in
            on a sample of the</p>

    </div>
</div>

{% endblock %}

web/templates/web/contact.html
{% extends 'base-main.html' %}

<title>{% block title %}Contacto - Comprando Presentes{% endblock %}</title>


{% block content %}


<div class="container" id="contact">
    <div class="row">
        <div class="col s12 m6">
            <h2>Contáctanos</h2>
            <p>Disponemos de diferentes plataformas para aclarar tus dudas o saber de ti.</p>

            <p>
                <i class="inline-icon material-icons">local_phone</i>
                <strong>Llámanos — </strong>
                <span>+56 9 903 03 456</span>
            </p>
            <p>
                <i class="inline-icon material-icons">email</i>
                <strong>Correo electrónico — </strong>
                <span>hagacaquita@appoo.cl</span>
            </p>
        </div>
        <div class="col s12 m6">

            <form method="post"> {% csrf_token %}

                    <div class="input-field col s12">
                        <input type="text" class="" id="id_name" name="name" required>
                        <label for="id_name">Nombre</label>
                    </div>
                    <div class="input-field col s12">
                        <input type="email" class="" id="id_sender" name="sender" required>
                        <label for="id_sender">Email</label>
                    </div>
                    <div class="input-field col s12">
                        <input type="text" class="" id="id_subject" name="subject" required>
                        <label for="id_subject">Asunto</label>
                    </div>
                    <div class="input-field col s12">
                        <textarea class="form-control materialize-textarea" rows="4" name="message" id="id_message" required></textarea>
                        <label for="id_message">Mensaje</label>
                    </div>
                    <div class="col s12">
                        <label>
                            <input type="checkbox" class="filled-out custom-checkbox" checked="checked" name="cc_myself" id="id_cc_myself"/>
                            <span>Deseo una copia</span>
                            <br/><br/> <hr/> <br/>
                        </label> 
                    </div>
                    <div class="col s12">
                        <button class="waves-effect waves-light btn green" type="submit">Enviar
                            <i class="inline-icon material-icons right">send</i>
                        </button>
                    </div>
                </div>
            </form>

        </div>

    </div>
</div>




<!-- Contact End -->

{% endblock %}

web/templates/web/enlaces.html
{% extends 'base-main.html' %}
{% load static %}

{% block title %}Enlaces{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">

        
        <h1 class="center">Enlaces</h1>
        <div class="col s12 m8 card offset-m2">
            {% for item in query_links %}
            <p>
                <i class="{{ item.icon}}"></i>
                <a href="{{ item.text }}" target="_blank">{{ item.title }}</a>
            </p>
            {% endfor %}
        </div>


    </div>
</div>

{% endblock %}

web/templates/web/escala.html
{% extends 'base-main.html' %}
{% load static %}

{% block title %}Escala de Bristol{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <h1 class="col s12 center">Escala de Bristol</h1>

        <div class="col s12 white card">
            <table class="highlight centered responsive-table">
                <thead>
                <tr>
                    <th>imagen</th>
                    <th>tipo</th>
                    <th>descripción</th>
                    <th>consejo</th>
                </tr>
                </thead>
        
                <tbody>
                    <tr>
                    {% for item in query_scale %}
                    
                        <td><img width="100px" src="{{ item.photo }}"/></td>
                        <td>{{ item.typesb }}</td>
                        <td>{{ item.text }}</td>
                        <td>{{ item.cause }}</td>
                    </tr>        
                    {% endfor %}
                </tbody>
            </table>
        </div>  
    </div>
</div>

{% endblock %}

web/templates/web/fotos.html
{% extends 'base-main.html' %}
{% load static %}

{% block title %}Galería{% endblock title %}

{% block content %}
<div class="parallax-container">
    <div class="joke">
        <h2>{{ query_photos.title }}</h2>
        <p>{{ query_photos.text }}</p>
    </div>

    <div class="parallax">
        <img src="{{ query_photos.photo }}">
    </div>
</div>

{% endblock %}

web/templates/web/home.html
{% extends 'base-main.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}

    <div class="parallax-container">
        <div class="parallax"><img src="{{ query_funfacts.photo }}"></div>
        

        <div class="card-me">
            <p class="txt1">
                {{ query_funfacts.title }}
            </p>
            <p class="txt2">
                {{ query_funfacts.text }}
            </p>
        </div>


    </div>


    <script>
        const card = [ 'card1', 'card2', 'card3', 'card4', 'card5', 'card6'];
        document.querySelector('.card-me').classList.add(card[Math.floor(Math.random() * card.length)]);
    </script>



{% endblock %}

web/templates/web/message_detail.html
{% extends 'base-main.html' %}

<title>{% block title %}Comentario - Comprando Presentes{% endblock %}</title>


{% block content %}


<div class="container">
    <div class="row">

        <br><br>

        <div class="col s12 card">
            <h4>Comentario</h4>
            {% if message.sending_date %}
            <p class="grey-text">
                {{ message.sending_date }}
            </p>{% endif %}
    
            <p class="grey-text">{{ message.name }} / {{ message.sender }}</p>
            <p class="flow-text">{{ message.message|linebreaksbr }}</p>

            {% if user.is_authenticated %}                            
            <a class="btn red" method="POST" href="{% url 'message_remove' pk=message.pk %}">Eliminar
                <i class="inline-icon material-icons">delete_forever</i>
            </a>               
            {% endif %}
            <br><br>
        </div>
    </div>
</div>


{% endblock %}

web/templates/web/message_list.html
{% extends 'base-main.html' %}
{% load static %}

<title>{% block title %}Comentarios-Comprando Presentes{% endblock %}</title>

{% block content %}

    <div class="container">
        <div class="row">
            <br><br>
            <div class="col s12 blue lighten-3">
                <h3>Comentarios</h3>
                <p>Consultas y sugerencias dejadas por nuestra comunidad</p>

                {% for message in messages %}

                    <div class="col s12 m4 card">
                        {% comment %}
                        
                        {% endcomment %}
                        <p>{{message.message}}</p>
                        <p class="grey-text"> <strong>{{message.name}}</strong></p>
                        <p class="grey-text">{{message.sender}}</p>
                    
                        
                    </div>

                {% endfor %} 

            </div>
        </div>
    </div>



{% endblock %}


web/templates/web/my_messages.html
{% extends 'base-main.html' %}
{% load static %}

<title>{% block title %}Mis Comentarios-Comprando Presentes{% endblock %}</title>

{% block content %}


<div class="container">
    <div class="row">

        <br><br>

        <div class="col s12 m10 offset-m1 blue lighten-3">
            <h3 class="center">Todos tus comentarios</h3>

            {% for my_message in my_messages %}
            <div class="col s12 m10 offset-m1 card">                    
                {% if my_message.sending_date %}
                <p id="published" class="grey-text">{{ my_message.sending_date }}</p>
                {% endif %}
                <p>{{my_message.message}}</p>
                <p>
                    <a href={% url 'message_detail' pk=my_message.pk %}>
                        <i class="material-icons">edit</i>
                        editar
                    </a> |
                   <span>{{my_message.name}}</span> |
                   <span>{{my_message.sender}}</span>


                <p>
                    {{my_messages.message}}
                </p>

            </div> 
            {% endfor %}  


        </div>





    </div>
</div>





{% endblock %}


web/templates/web/recomendaciones.html
{% extends 'base-main.html' %}
{% load static %}

{% block title %}Recomendaciones{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        
        <h1 class="center">Recomendaciones</h1>
        {% for item in query_tips %}
        <div class="card blue lighten-4 col s12 m8 offset-m2 section">
            <h4>
                <i class="{{ item.icon }}"></i>
                {{ item.title }}</h4>
            <p>{{ item.text }}</p>
        </div>  
        {% endfor %}
      
    </div>
</div>

{% endblock %}

web/templates/web/success.html
{% extends 'base-main.html' %}
{% load static %}


<title>{% block title %}Mensaje recibido{% endblock %}</title>


{% block content %}


    <div class="container">
        <div class="row">
            <br><br>
            <div class="col card s12 m8 offset-m2 center">
                <h3 class="green-text">Mensaje Recibido Exitosamente</h3>
                <p class="flow-text">Un integrante de nuestra área de atención responderá a tu solicitud lo más pronto posible</p>
                <p class="flow-text">¡Gracias por contactarnos!</p>
                <br><br>
                <a class="waves-effect waves-light btn green darken-3" href="{% url 'message_list' %}">
                    Comentarios
                    <i class="material-icons left">comment</i>
                </a>
                <br><br>             
            </div>
        </div>
    </div>


    
{% endblock %}